#+++++++++++++++++++++++++++++++++++++++++++
#Temperature presets
#+++++++++++++++++++++++++++++++++++++++++++

[preheat LEVELING]
extruder: 150
heater_bed: 60
# GCode to run when the option is selected
gcode: PRECALENTAR_LEVELING
       #Beep

[preheat PLA]
extruder: 195
heater_bed: 60
# GCode to run when the option is selected
gcode: PRECALENTAR_PLA
       #Beep

[preheat PETG]
extruder: 240
heater_bed: 80
# GCode to run when the option is selected
gcode: PRECALENTAR_PETG
       #Beep

[preheat ABS]
extruder: 220
heater_bed: 90
# GCode to run when the option is selected
gcode: PRECALENTAR_ABS
       #Beep

[preheat ASA]
extruder: 220
heater_bed: 90
# GCode to run when the option is selected
gcode: PRECALENTAR_ASA
       #Beep

[preheat FLEX]
extruder: 210
heater_bed: 50
# GCode to run when the option is selected
gcode: PRECALENTAR_FLEX
       #Beep

[preheat HIPS]
extruder: 220
heater_bed: 110
# GCode to run when the option is selected
gcode: PRECALENTAR_FLEX
       #Beep

[preheat Limpieza]
extruder: 240
# heater_bed: 5
# GCode to run when the option is selected
gcode: PRECALENTAR_LIMPIEZA
       #Beep

#+++++++++++++++++++++++++++++++++++++++++++
#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = blurry2
#~# 24htime = False
#~# use_dpms = False
#~# show_scroll_steppers = True
#~# print_sort_dir = date_desc
#~# language = en
#~#
